### ISSUE TITLE
PlayStore Link Not working

### ISSUE THREAD

**Issue by sharadcodes** [rizmaulana/kotlin-mvvm-covid19#19]

**Comment by pandubaraja** [comment]
Hi @rizmaulana @isfaaghyth @fajarnuha, I cant find it either 
![image](https://user-images.githubusercontent.com/30037407/76701765-a4bc1900-66f6-11ea-896d-7725ea0899cd.png)

**Comment by isfaaghyth** [comment]
It seems Google doesn't allow applications related for Covid-19 on playstore. Bump @rizmaulana

**Comment by rizmaulana** [comment]
Sorry for late response, yes @isfaaghyth @pandubaraja @fajarnuha  it is suspended by google because of sensitive data.
You can download it [here](https://drive.google.com/open?id=1gLceG2C_TvwsVpYNqJ_PiQFBsofib2iK), I will upload apk with latest feature to this google drive folder while I will try setup github CI/CD + Fastlane + Firebase App Distribution to deliver app.
Will update readme.MD with link.
